# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:5000/
Accept: application/json

###
POST http://192.168.56.56:5000/api/register
Content-Type: application/json

{
    "username": "Jerry",
    "password": "admin123"
    "workcode": 1123
}

###
POST http://192.168.56.56:5000/api/login
Content-Type: application/json

{
    "username": "Jerry",
    "password": "admin123"
}

###
GET http://192.168.56.56:5000/api/getUserList
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4OTYwNTUyOSwianRpIjoiYTg5M2EyMzMtMjljMi00MmM3LTk4NGItNjQ5YjA1ZWZhMTJiIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkplcnJ5IiwibmJmIjoxNjg5NjA1NTI5LCJleHAiOjE2ODk2MTI3Mjl9.f65LLa9xJE9mMtS_CiwdZj4GdDpkFpBmH7ULMr74fFg

###
