"""empty message

Revision ID: 74b8d1c1bb9a
Revises: c0c97b453137
Create Date: 2023-07-20 17:00:13.025127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74b8d1c1bb9a'
down_revision = 'c0c97b453137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workcode', sa.Integer(), nullable=False, comment='工号'))
        batch_op.drop_column('wokecode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wokecode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='工号'))
        batch_op.drop_column('workcode')

    # ### end Alembic commands ###
