"""empty message

Revision ID: c0c97b453137
Revises: a1fecf02c842
Create Date: 2023-07-20 16:28:16.365794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c97b453137'
down_revision = 'a1fecf02c842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wokecode', sa.Integer(), nullable=False, comment='工号'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wokecode')

    # ### end Alembic commands ###
